site:
  title: SKALE Network Documentation 
  start_page: ROOT::index.adoc
  robots: allow
content:
  sources:
    - url: .
      branches: HEAD
      start_path: components/home

    - url: .
      branches: HEAD
      start_path: components/learn

    - url: .
      branches: HEAD
      start_path: components/recipes

    - url: .
      branches: HEAD
      start_path: components/validators

    - url: .
      branches: HEAD
      start_path: components/develop
    
    - url: .
      branches: HEAD
      start_path: components/infrastructure
      
    - url: .
      branches: HEAD
      start_path: components/filestorage

    - url: .
      branches: HEAD
      start_path: components/technology

    - url: .
      branches: HEAD
      start_path: components/partnership

    - url: https://github.com/skalenetwork/skale-manager
      branches: docs-v*
      start_path: docs

    - url: https://github.com/skalenetwork/filestorage.js
      branches: docs-v*
      start_path: docs

    - url: https://github.com/skalenetwork/skaled
      branches: docs-v*
      start_path: docs

    - url: https://github.com/skalenetwork/IMA
      branches: docs-v*
      start_path: docs

    - url: https://github.com/skalenetwork/skale-watchdog
      branches: docs-v*
      start_path: docs

    - url: https://github.com/skalenetwork/node-cli
      branches: docs-v*
      start_path: docs

    - url: https://github.com/skalenetwork/validator-cli
      branches: docs-v*
      start_path: docs

    - url: https://github.com/skalenetwork/skale-node
      branches: docs-v*
      start_path: docs

    - url: https://github.com/skalenetwork/metaport
      branches: docs-v*
      start_path: docs
      
ui:
  bundle:
    url: ./doc-ui/build/sn-docs-ui-bundle.zip
  supplemental_files: ./doc-ui/static
    # snapshot: true
asciidoc:
  attributes:
    :plantuml-server-url: http://www.plantuml.com/plantuml
  extensions:
  - ./lib/tabs-block.js
  - '@djencks/asciidoctor-mathjax'
  - 'asciidoctor-kroki'
urls:
  redirect_facility: netlify
