site:
  title: Developers 
  url: https://skale.network/docs
  start_page: skalenetwork::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: components/home

    - url: https://github.com/skalenetwork/skale-manager
      branches: docs-v*
      start_path: docs

    - url: https://github.com/skalenetwork/filestorage.js
      branches: docs-v*
      start_path: docs

    - url: https://github.com/skalenetwork/skaled
      branches: docs-v*
      start_path: docs

    - url: https://github.com/skalenetwork/IMA
      branches: docs-v*
      start_path: docs

    - url: https://github.com/skalenetwork/skale-watchdog
      branches: docs-v*
      start_path: docs
      
ui:
  bundle:
    url: ./ui/build/sn-docs-ui-bundle.zip
    # snapshot: true
asciidoc:
  extensions:
  - ./lib/tabs-block.js